CREATE TABLE IF NOT EXISTS ai_request_trace (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    request_id VARCHAR(64) NOT NULL UNIQUE,
    memory_id VARCHAR(128) NOT NULL,
    tenant_id BIGINT NULL,
    user_id VARCHAR(128) NULL,
    question MEDIUMTEXT,
    response MEDIUMTEXT,
    status VARCHAR(32) NOT NULL,
    error_message TEXT,
    model_name VARCHAR(128),
    finish_reason VARCHAR(64),
    latency_ms BIGINT,
    first_token_latency_ms BIGINT,
    streamed_chars INT,
    input_tokens INT,
    output_tokens INT,
    total_tokens INT,
    retrieved_count INT,
    top_retrieval_score DOUBLE,
    retrieval_rejected_reason VARCHAR(128),
    tool_call_count INT,
    evaluation_score INT,
    evaluation_status VARCHAR(32),
    risk_level VARCHAR(32),
    evaluation_reasons_json TEXT,
    retrieval_snapshot_json MEDIUMTEXT,
    started_at DATETIME NOT NULL,
    completed_at DATETIME NULL,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    INDEX idx_ai_request_trace_started_at (started_at),
    INDEX idx_ai_request_trace_memory_id (memory_id),
    INDEX idx_ai_request_trace_user_id (user_id),
    INDEX idx_ai_request_trace_status (status),
    INDEX idx_ai_request_trace_risk_level (risk_level)
);

CREATE TABLE IF NOT EXISTS ai_tool_trace (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    request_id VARCHAR(64) NOT NULL,
    sequence_no INT NOT NULL,
    tool_name VARCHAR(128) NOT NULL,
    arguments_json TEXT,
    result_preview TEXT,
    success TINYINT(1) NOT NULL,
    error_message TEXT,
    created_at DATETIME NOT NULL,
    INDEX idx_ai_tool_trace_request_id (request_id),
    CONSTRAINT fk_ai_tool_trace_request FOREIGN KEY (request_id) REFERENCES ai_request_trace(request_id)
);
